### ISSUE TITLE
Microsoft.Azure.Kusto.Data v10.1.0 - Kusto socket exception

### ISSUE THREAD

**Issue by kpobb1989** [Azure/azure-kusto-dotnet#3]
The latest version of the package throws socket exception when an app tries to connect to kusto from azure cloud. However on the local machine it is working fine.

Here the error message:
Kusto client failed to send a request to the service: 'An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.'

The best solution we were able to find is to downgrade the version of the package like it's described on [stackoverflow](https://stackoverflow.com/questions/73218629/access-azure-data-explorer-with-kusto-data-in-azure-function-kusto-failed-to)

Please take a look at it in priority. Thanks.

**Comment by kwirkykat** [comment]
+1
We are also seeing this socket exception when trying to execute a Kusto query from an Azure Function.
We didn't change anything other than updating to the new SDK version.

Here's the line of code where we call:
dataSet = await this.queryProvider.ExecuteQueryAsync(databaseName, query, null);

Here's the stack trace:
System.Net.Sockets.SocketException (10042): An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at Kusto.Data.Net.Client.RestClient2.ConnectCallbackAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
  ([0]Kusto.Data.Exceptions.KustoClientException.StackTrace:)
   at Kusto.Data.Net.Client.RestClient2.MakeHttpRequestAsyncImpl(String address, String csl, String ns, String databaseName, Boolean streaming, ClientRequestProperties properties, ServiceModelTimeoutKind timeoutKind, String clientRequestId, Stream body, StreamProperties streamProperties, CancellationToken cancellationToken, KustoProtocolRequest request)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Data.Net.Client.RestClient2.MakeHttpRequestAsync(ActivityType activityType, String baseAddress, String relativeAddress, String clientRequestIdPrefix, String ns, String databaseName, String csl, String addr, Boolean streaming, ClientRequestProperties properties, ServiceModelTimeoutKind timeoutKind, StreamProperties streamProperties, CancellationToken cancellationToken)
   at Kusto.Data.Net.Client.RestClient2.ExecuteQueryAsync(String databaseName, String query, ClientRequestProperties properties)

**Comment by a99cl208** [comment]
Same behavior here on an App Service deployment, and it works locally. I noticed that on the latest version all targets are based on .NET 6.0.8 which was not the case before:
![image](https://user-images.githubusercontent.com/9946659/186522466-c4d74524-7df5-4113-a908-ad6e9202e536.png)

This may be a hint.

**Comment by nsulikowski** [comment]
Same problem with 10.1.1. Got resolved when downgrading to 10.0.2

**Comment by a99cl208** [comment]
The version 11.0.0 fixed the issue for me.

**Comment by nsulikowski** [comment]
Yep 11.0.0 worked for me too

**Comment by kpobb1989** [comment]
The issue was solved in v11
